# Site
repository: dali-does/thesis-page

# Content configuration version
version: 2

# Personal info
name: Adam Dahlgren Lindstrom
title: PhD student
email: dali@cs.umu.se
website: TBA
# website_title: Web (Website title override)

# Dark Mode (true/false/never)
darkmode: false

# Social links
#twitter_username: jekyllrb
github_username:  dali-does
orcid_username: 0000-0002-1112-2981
googlescholar_username: LctkPQgAAAAJ

# Additional icon links
additional_links:
- title: Google Scholar name
  icon: Font Awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&s=brands&m=free)
  url: Link url (eg. https://google.com)

# About Section
# about_title: About Me (Use this to override about section title)
about_profile_image: https://www.umu.se/contentassets/82f461f9a9e44e6ba31f462e79da1849/Profilbild.jpg?v=1283924955
about_content: | # this will include new lines to allow paragraphs
  Internal page to keep relevant people informed of thesis work and progress.

  You can even add paragraphs by using empty lines like this and add anything else [markdown](https://www.markdownguide.org/getting-started#what-is-markdown) supports such as
    - Lists
    - Tables
    - <a href="google.com">Links</a>

content:
  - title: Research Questions
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        border: weak  # Value of `weak` will display a weak border below this item. # Any
                      # other value (or no value) means no border will be displayed
        title: RQ 1
        quote: >
          Short overview of the project (optional)
        description: | # this will include new lines to allow paragraphs
          Description about the work on/with the project
  - title: Published work # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        border: weak  # Value of `weak` will display a weak border below this item. # Any
                      # other value (or no value) means no border will be displayed
        title: Probing COLING
        link: Link to project (eg. sproogen.github.io/modern-resume-theme)(optional)
        link_text: Link Text
        additional_links:
          - title:  Github page for project (eg. sproogen/modern-resume-theme)
            icon: fab fa-github
            url: Link to project (eg. sproogen.github.io/modern-resume-theme)(optional)
          - title:  Github page for project (eg. sproogen/modern-resume-theme)
            icon: fab fa-github
            url: Link to project (eg. sproogen.github.io/modern-resume-theme)(optional)
        quote: >
          Short overview of the project (optional)
        description: | # this will include new lines to allow paragraphs
          Description about the work on/with the project

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/modern-resume-theme (Use this if you are hosting your resume on GitHub)

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

exclude : [
  "Gemfile",
  "Gemfile.lock",
  "node_modules",
  "vendor/bundle/",
  "vendor/cache/",
  "vendor/gems/",
  "vendor/ruby/",
  "lib/",
  "scripts/",
  "docker-compose.yml",
  ]

# Site
repository: dali-does/thesis-page

version: 2
favicon: images/favicon.ico

# Personal info
name: Adam Dahlgren Lindstrom
title: PhD student
email: dali@cs.umu.se
website: TBA
# website_title: Web (Website title override)

# Dark Mode (true/false/never)
darkmode: false

# Social links
#twitter_username: jekyllrb
github_username:  dali-does
orcid_username: 0000-0002-1112-2981
googlescholar_username: LctkPQgAAAAJ


# About Section
# about_title: About Me
about_profile_image: https://www.umu.se/contentassets/82f461f9a9e44e6ba31f462e79da1849/Profilbild.jpg?v=1283924955
about_content: |
  Hi, my name is Adam Dahlgren Lindström, this is a website to keep relevant parties informed on the progress of my thesis writing.

content:
  - title: RQs# Title for the section
    layout: list
    content:
      - layout: top-middle
        border: weak
        title: RQ 1
        quote: >
          A modern simple static resume template and theme. Powered by Jekyll and GitHub pages.
        description: |
          This is a <mark>Jekyll</mark> theme that I have recently created, in fact it is what this resume has been built with.

  - title: Published work
    layout: list
    content:
      - layout: left
        border: weak
        title: Probing
        sub_title: Probing ...
        caption: COLING 2020
        description: |
          Taken accountability for the frontend of the payments product area within a commercial banking platform, becoming a go to for knowledge and technical decisions.

# Footer
footer_show_references: false

# Build settings
remote_theme: sproogen/resume-theme

# sass:
#   style: compressed
